sudo: required
go:
- 1.9
node_js:
- 8
jobs:
  include:
  - stage: Build Docker Images
    language: go
    services:
    - docker
    install: "./bin/ci/build_imgs_install.sh"
    script:
    - "./bin/ci/build_imgs_solutions.sh"
    - "./bin/ci/build_imgs_push.sh"
env:
  matrix:
    - TARGET=rfv
    - TARGET=eng
    - BRANCH=develop
    - BRANCH=master