sudo: required
language: go
go:
- 1.9
node_js:
- 8
services:
- docker
install: echo "Installing"
script: echo "Scripting"
jobs:
  include:
  - stage: Robot Tests
    install: echo "Robot Tests install $TARGET"
    script: echo "Robot tests scripts $TARGET"
env:
    - TARGET=rfv